version: 0.0
os: linux
files:
    - source: /MidhunKandiyilMeethal-php-final-app-c06f081
    destination: /var/www/html
    overwrite: true
hooks:
  BeforeInstall:
        - location: scripts/install.sh
      timeout: 300
      runas: root
